name: 'Release'
description: 'Upload artifacts to a release'
inputs:
  file:
    description: The file to upload
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
outputs:
  url:
    description: 'URL to the Release HTML Page'
runs:
  using: 'node12'
  main: 'main.js'
